name: jupyter-version
channels:
  - anaconda
  - defaults
dependencies:
  - ipywidgets
  - matplotlib
  - notebook
  - numpy
  - pandas=0.25
  - python=3.7
  - seaborn
  - scikit-learn
  - pip
  - pip:
      - coverage
      - dynaconf
      - fbprophet
      - jupyterlab
      - loguru
      - mlflow==1.8.0
      - plotly==4.12.0





