name: jupyter-version
channels:
  -  defaults
  -  anaconda
dependencies:
  - python==3.6
  - numpy
  - notebook
  - pandas 
  - scikit-learn
  - seaborn
  - matplotlib
  - ipywidgets
  - pip
  - pip:
     - jupyterlab
     - mlflow

